<a href="https://colab.research.google.com/github/Shikigamiii/BSIS_2A_ACTIVITIES-/blob/main/Las_igan_Mcgyver_R.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [27]:
import pandas as pd

In [28]:
df = pd.read_csv('https://raw.githubusercontent.com/Shikigamiii/BSIS_2A_ACTIVITIES-/main/RailsToTrails_National%20Count%20Data_week.csv')

In [29]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 52 entries, 0 to 51
Data columns (total 10 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Timeframe                   52 non-null     object
 1   Week of                     52 non-null     object
 2    2019 counts (31 counters)  52 non-null     int64
 3    2020 counts (31 counters)  52 non-null     int64
 4   2021 Counts                 0 non-null      float64
 5   Change 2019-2020            52 non-null     object
 6   Unnamed: 6                  52 non-null     float64
 7   Unnamed: 7                  0 non-null      float64
 8   Unnamed: 8                  1 non-null      object
 9   Unnamed: 9                  1 non-null      float64
dtypes: float64(4), int64(2), object(4)
memory usage: 4.2+ KB

In [30]:
df.head()

,Timeframe,Week of,2019 counts (31 counters),2020 counts (31 counters),2021 Counts,Change 2019-2020,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9
0,Week 1,30-Dec,167679,183546,NaN,9%,1.094627,NaN,NaN,NaN
1,Week 2,6-Jan,82340,97140,NaN,18%,117.974253,NaN,NaN,NaN
2,Week 3,13-Jan,62315,75782,NaN,22%,121.611169,NaN,NaN,NaN
3,Week 4,20-Jan,75801,83809,NaN,11%,110.564504,NaN,NaN,NaN
4,Week 5,27-Jan,75841,94738,NaN,25%,124.916602,NaN,NaN,NaN

In [31]:
df = df.drop(columns=['Unnamed: 7','Unnamed: 8','Unnamed: 9'])

In [34]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 52 entries, 0 to 51
Data columns (total 7 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Timeframe                   52 non-null     object
 1   Week of                     52 non-null     object
 2    2019 counts (31 counters)  52 non-null     int64
 3    2020 counts (31 counters)  52 non-null     int64
 4   2021 Counts                 0 non-null      float64
 5   Change 2019-2020            52 non-null     object
 6   percent_change              52 non-null     float64
dtypes: float64(2), int64(2), object(3)
memory usage: 3.0+ KB

In [35]:
df = df.rename(columns={'Unnamed: 6': 'percent_change'})

In [36]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 52 entries, 0 to 51
Data columns (total 7 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Timeframe                   52 non-null     object
 1   Week of                     52 non-null     object
 2    2019 counts (31 counters)  52 non-null     int64
 3    2020 counts (31 counters)  52 non-null     int64
 4   2021 Counts                 0 non-null      float64
 5   Change 2019-2020            52 non-null     object
 6   percent_change              52 non-null     float64
dtypes: float64(2), int64(2), object(3)
memory usage: 3.0+ KB

In [37]:
df.isna()

,Timeframe,Week of,2019 counts (31 counters),2020 counts (31 counters),2021 Counts,Change 2019-2020,percent_change
0,False,False,False,False,True,False,False
1,False,False,False,False,True,False,False
2,False,False,False,False,True,False,False
3,False,False,False,False,True,False,False
4,False,False,False,False,True,False,False
5,False,False,False,False,True,False,False
6,False,False,False,False,True,False,False
7,False,False,False,False,True,False,False
8,False,False,False,False,True,False,False
9,False,False,False,False,True,False,False
10,False,False,False,False,True,False,False
11,False,False,False,False,True,False,False
12,False,False,False,False,True,False,False
13,False,False,False,False,True,False,False
14,False,False,False,False,True,False,False
15,False,False,False,False,True,False,False
16,False,False,False,False,True,False,False
17,False,False,False,False,True,False,False
18,False,False,False,False,True,False,False
19,False,False,False,False,True,False,False
20,False,False,False,False,True,False,False
21,False,False,False,False,True,False,False
22,False,False,False,False,True,False,False
23,False,False,False,False,True,False,False
24,False,False,False,False,True,False,False
25,False,False,False,False,True,False,False
26,False,False,False,False,True,False,False
27,False,False,False,False,True,False,False
28,False,False,False,False,True,False,False
29,False,False,False,False,True,False,False
30,False,False,False,False,True,False,False
31,False,False,False,False,True,False,False
32,False,False,False,False,True,False,False
33,False,False,False,False,True,False,False
34,False,False,False,False,True,False,False
35,False,False,False,False,True,False,False
36,False,False,False,False,True,False,False
37,False,False,False,False,True,False,False
38,False,False,False,False,True,False,False
39,False,False,False,False,True,False,False
40,False,False,False,False,True,False,False
41,False,False,False,False,True,False,False
42,False,False,False,False,True,False,False
43,False,False,False,False,True,False,False
44,False,False,False,False,True,False,False
45,False,False,False,False,True,False,False
46,False,False,False,False,True,False,False
47,False,False,False,False,True,False,False
48,False,False,False,False,True,False,False
49,False,False,False,False,True,False,False
50,False,False,False,False,True,False,False
51,False,False,False,False,True,False,False

In [38]:
df.isna().sum()

Timeframe                      0
Week of                        0
 2019 counts (31 counters)     0
 2020 counts (31 counters)     0
2021 Counts                   52
Change 2019-2020               0
percent_change                 0
dtype: int64

In [39]:
df['2021 Counts'].fillna('missing', inplace=True)

In [40]:
df.isna().sum()

Timeframe                     0
Week of                       0
 2019 counts (31 counters)    0
 2020 counts (31 counters)    0
2021 Counts                   0
Change 2019-2020              0
percent_change                0
dtype: int64

In [41]:
df = df.rename(columns={' 2019 counts (31 counters)': 'counts_2019 (12 Pogime)'})

In [42]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 52 entries, 0 to 51
Data columns (total 7 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Timeframe                   52 non-null     object
 1   Week of                     52 non-null     object
 2   counts_2019 (12 Pogime)     52 non-null     int64
 3    2020 counts (31 counters)  52 non-null     int64
 4   2021 Counts                 52 non-null     object
 5   Change 2019-2020            52 non-null     object
 6   percent_change              52 non-null     float64
dtypes: float64(1), int64(2), object(4)
memory usage: 3.0+ KB